### ISSUE TITLE
Security: XSS Attack against "info"-hover items

### ISSUE THREAD

**Issue by skx** [wallaby-rails/wallaby-rails#107]
* Create a tag with the name `"><script>alert('steve');</script>`.
* Visit the tags page
  * https://wallaby-demo.herokuapp.com/admin/tags

You'll notice the tag-name is truncated - and there is an "(i)" symbol:

![1](https://user-images.githubusercontent.com/735291/41289396-46da78a2-6e52-11e8-9404-b06933c63975.jpg)

Hover over that (i) symbol:

![2](https://user-images.githubusercontent.com/735291/41289426-5c96b746-6e52-11e8-934b-1094c791f7aa.jpg)

Obviously this just shows an alert.  The login-session cookie could be stolen, or things deleted..

**Comment by skx** [comment]
**NOTE**: Same thing seems to happen on product-names, etc.  Anything with the hover-"(i)" behaviour.

Also you can simplify the j/script to just `<script>alert(33);</script>`.  No need for the leading `">`.

**Comment by tian-im** [comment]
Good finding! Thanks @skx will do a fix for this soon

**Comment by tian-im** [comment]
@skx, patch is in the latest release [5.1.8](https://github.com/reinteractive/wallaby/releases/tag/5.1.8). Therefore, I'm going to close this issue now.

Please let me know if you find more security issues. Cheers
