### ISSUE TITLE
How to create custom types?

### ISSUE THREAD

**Issue by josephfarina** [wallaby-rails/wallaby-rails#109]
Hello,

Wallaby looks great, but I am a bit confused by the docs:

I see this:

```
    # Or you can update its type to `raw`
    # `raw` is built-in type to render HTML instead of escaping the HTML tags and entities.
    self.index_fields[:description][:type] = 'raw'
```

and I am wondering where I would put the HTML that is generated?

For example: how do you create custom inputs? Like if i wanted one main input and a couple other hidden ones that are derived from the first one using JavaScript. How would I go about doing that using wallaby?

Thanks!

**Comment by tian-im** [comment]
Hey @JosephFarina,

The document [Decorator](https://github.com/reinteractive/wallaby/blob/master/docs/decorator.md) describes how to configure the type, and document [View](https://github.com/reinteractive/wallaby/blob/master/docs/view.md) has more details about how you can create custom type.

In your example, if you want to create custom inputs, you should:
1. Update the type in the decorator

  ```ruby
  self.form_fields[:description][:type] = 'custom_type_for_description'
  ```

2. Create the type partial at `app/views/admin/product/form/_custom_type_for_description.html.erb`, see [here](https://github.com/reinteractive/wallaby/blob/master/docs/view.md#local-variables) for what local variables you have access to:
  ```erb
  <%= form.text_area field_name %>
  <%= form.hidden_field 'a' %>
  <%= form.hidden_field 'b' %>
  <% content_for :custom_javascript do %>
    <%# This will be injected into the bottom of <BODY> tag %>
    <% javascript_tag do %>
      alert('This will get executed multiple type if there are more than one custom_type_for_description is used on the same page');
    <% end %>
  <% end %>
  ```

3. Or create and modify js file `app/assets/javascript/wallaby/application.js`

  ```javascript
  //= require wallaby/base
  // begin your custom javascript below
  alert('This will be executed on page load');
  ```

And that's it.

Let me know if you have more questions.

Tian

**Comment by tian-im** [comment]
I hope no news is good news and am going to close this issue now
