### ISSUE TITLE
Uninitialized constant CanCan

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#165]
It appears `cancancan` was removed as a gem dependency however `app/security/ability.rb` in `wallaby-core` still references it. This results in the error: `uninitialized constant CanCan (NameError)` when the file is loaded.

You may only see this error when eager loading is enabled in the Rails app environment config.

**Comment by tian-im** [comment]
See the above fix. I will make a release soon. Will let you know.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.1 and see if it works for you?

**Comment by ryanb** [comment]
Looks like it works!
