### ISSUE TITLE
I18n locales don't have wallaby namespace

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#166]
It appears the locales in wallaby-core `config/locales/wallaby.en.yml` are not scoped under a `wallaby` key. This results in two issues:

* These locales could conflict with other locales in the app.
* If one needs to add these locales in their app (if they don't have `en` locale) it isn't clear it is for Wallaby.

**Comment by tian-im** [comment]
Yep, Mikel mentioned that as well. I will take it to a higher priority now.

**Comment by tian-im** [comment]
Done. it's in `wallaby-core` master now

**Comment by ryanb** [comment]
@tian-im why isn't `fa` scoped under `wallaby`? Isn't it a locale used by wallaby?

**Comment by ryanb** [comment]
@tian-im also can you update the `wallaby` repo since that uses locales too.

**Comment by tian-im** [comment]
I was thinking to leave `fa` as it's more like a config rather than locale. but yeah, it seems like there isn't any drawback by putting it under `wallaby` scope as well. will fix it

**Comment by ryanb** [comment]
Thanks. It seems strange to put `fa` under I18n. Do you want it to behave differently for different translations?

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.1 and see if it works for you?

**Comment by ryanb** [comment]
This looks good, thanks!
