### ISSUE TITLE
Conflict with current_user method

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#167]
It appears the `current_user` method is being overridden in [Wallaby::SecureController](https://github.com/wallaby-rails/wallaby-core/blob/master/app/controllers/wallaby/secure_controller.rb#L41).

This can conflict with the existing `current_user` method defined in the app. For example, we have `current_user` and `current_admin_user` and we want to use the latter for Wallaby. The issue is the `current_user` method within Wallaby controller subclasses returns an `AdminUser` instance instead of a normal `User`.

This causes confusion and everything in our main ApplicationController needs to check which type of user is being returned by `current_user`.

I suggest renaming `current_user` to `wallaby_current_user` and use that in Wallaby internals.

**Comment by tian-im** [comment]
Regarding the `current_user` in Wallaby's controller, it does override the one from `::ApplicationController`, but it will call `super` when it's defined. Therefore, it should work the same as `::ApplicationController`.

And `current_user` in Wallaby acts as a template method that allows a dev to override in `Admin::ApplicationController`. For example, if `current_admin_user` is the one that you wish to use, then it can go as:

```ruby
class Admin::ApplicationController < Wallaby::ResourcesController
  def current_user
    current_admin_user
  end
end
```

As `current_user` is the convention that most Rails app use, but if it's confusing, I can rename it to something like `wallaby_user`.

What do you think?

**Comment by ryanb** [comment]
@tian-im The problem is overriding `current_user` causes it to return a different class instance than the rest of the application. This causes confusion because we don't know which instance it is returning (User or AdminUser).

Let's say we have a `before_filter` on `::ApplicationController` which references `current_user`. This filter will be triggered in both our app and Wallaby so we need to check if `current_user` is `User` or `AdminUser` to determine how to interact with it.

Please rename it to something wallaby specific and then use that in all internal methods.

**Comment by tian-im** [comment]
I see, will rename it to `wallaby_user` (similar to `pundit_user`). Will let you know once it's ready.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.2 and see if it works for you? `wallaby_user` is now used, and I will remove the `current_user` configuration from future version.

**Comment by ryanb** [comment]
@tian-im I'm a bit confused about this one. Since the `current_user` config is deprecated, what is the alternative? It is still mentioned in the docs here: https://github.com/wallaby-rails/wallaby/blob/master/docs/configuration.md#authenticate

I tried overriding `wallaby_user` method in the controller which seems to work but I still see this in the logs:

```
WALLABY DEPRECATED: Wallaby will remove security.current_user? from 6.2.
from /Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/wallaby-core-0.2.2/lib/wallaby/configuration/security.rb:61:in `current_user'
WALLABY DEPRECATED: Wallaby will use `wallaby_user` instead of `current_user` from 6.2.
from /Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/wallaby-core-0.2.2/lib/concerns/wallaby/authentication_concern.rb:105:in `current_user'
WALLABY DEPRECATED: Wallaby will remove security.authenticate from 6.2.
from /Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/wallaby-core-0.2.2/lib/wallaby/configuration/security.rb:86:in `authenticate'
WALLABY DEPRECATED: Wallaby will use `authenticate_wallaby_user!`instead of `authenticate_user!` from 6.2.
from /Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/wallaby-core-0.2.2/lib/concerns/wallaby/authentication_concern.rb:117:in `authenticate_user!'
```

Any idea how to remove these deprecation warnings?

**Comment by tian-im** [comment]
@ryanb I think you have to override both `wallaby_user` and `authenticate_wallaby_user!` method at the same time to get rid of the warnings. let me update the document later on.

**Comment by tian-im** [comment]
Because the authentication is still using devise's `authenticated` method which is still calling the `current_user` method.

**Comment by ryanb** [comment]
Overriding `authenticate_wallaby_user!` got rid of the last two deprecation warnings, but the first two are still showing up. I think because we have some filters in `::ApplicationController` which call `current_user` not wanting the admin user but the normal user.

Since there's no way to distinguish between these legitimate calls and the incorrect calls, I'll just ignore those deprecation warnings until 6.2 is released. Closing this, thanks!

**Comment by ryanb** [comment]
I ended up doing this in the admin application controller:

```
# Override `current_user` to the default Devise behavior.
# This can be removed after Wallaby 6.2 is released.
def current_user
  @current_user ||= warden.authenticate(scope: :user)
end

def wallaby_user
  @wallaby_user ||= current_admin_user
end

def authenticate_wallaby_user!
  authenticate_admin_user!
end
```

This removes all deprecation warnings and has the behavior I want.
