### ISSUE TITLE
Incompatibility with PaperTrail

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#176]
I have a model which `has_paper_trail` using the [paper_trail gem](https://github.com/paper-trail-gem/paper_trail). When visiting the `show` action of this model it attempts to render the internal `has_many :versions` association that PaperTrail sets up and results in this error:

```
NoMethodError - undefined method `to_label' for #<PaperTrail::Version:0x00007f8ca4983338>
Did you mean?  to_global_id
```

This is a rather confusing error message. The logs show this:

```
[WALLABY] Don't know how to handle this model PaperTrail::Version.
```

Perhaps raise an error on this which is more informative. Also maybe some information on how to resolve the problem.

I first tried adding it to `config.models.exclude` but that didn't seem to remove the error.

I then added it to `config.custom_models` which appears to have worked. However the Versions section attempts to link to that version and a link to create versions. Maybe disable the link if it's an excluded model?

**Comment by tian-im** [comment]
there is a way to get around this by taking out the versions from the `show_field_names`:

```ruby
class Model
  show_field_names.delete 'versions'
end
```

And at the same time, I will see if I can fix this on Wallaby side or take the versions out from the index field lists.

**Comment by tian-im** [comment]
But it's weird, Wallaby should be able to recognize and handle `PaperTrail::Version` model. Unless PaperTrail is loaded after Wallaby. Hmmm

**Comment by ryanb** [comment]
Paper trail is listed before wallaby in our gemfile but I'm not certain how it handles loading internally.

**Comment by tian-im** [comment]
Do you have the branch that you get this issue? Maybe I can take a look

**Comment by ryanb** [comment]
@tian-im The branch on Envisage is `epic/rails-6`. It is mostly working with the `custom_models` and `models.exclude` configs.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.2 and see if it works for you?

**Comment by ryanb** [comment]
Works great, thanks!
