### ISSUE TITLE
Changing code falls back to ApplicationDecorator

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#178]
I'm getting strange behavior after changing code and reloading the page. Sometimes the code changes don't take effect, but other times it loses reference to the custom decorators and templates.

I've been able to duplicate this on the demo app after upgrading to Wallaby 6. Updating a decorator's code and reloading the page seems to cause all decorators to reference `ApplicationDecorator`. Also custom templates like `views/products/edit.html.erb` no longer render instead fall back to their default templates.

Restarting the app fixes the problem until the code changes again.

**Comment by tian-im** [comment]
Yeah, I think this is related to incorrect reload. Let's see if the caching String instead of Class in Wallaby::Map fixes this or not.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.2 and see if it works for you?

**Comment by ryanb** [comment]
Yes I believe this is fixed.
