### ISSUE TITLE
Add context to default authorization provider

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#179]
The `DefaultAuthorizationProvider.args_from` method returns an empty hash so it doesn't track any args. It would be nice if it passed the `context` so we have access to that in the app's `ApplicationAuthorizer`.

Currently what I'm doing is inheriting from `DefaultAuthorizationProvider` with a custom provider class that tracks the user.

**Comment by tian-im** [comment]
Just realized that I've updated the document to use `context`, but it wasn't actually implemented 😭 Now as the PR is merged, I will do a release soon.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.2 and see if it works for you? the `args_from` has been taken out from the providers, but you should be able to access the `context` from either the authorizer itself or the `provider` attribute. For example:

```ruby
class ApplicationAuthorizer < Wallaby::ModelAuthorizer
  def return_path
    provider.context.root_path
    # or
    context.root_path
  end
end
```

**Comment by ryanb** [comment]
This works, thanks!
