### ISSUE TITLE
Error: A copy of ApplicationAuthorizer has been removed but is still active

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#181]
I am running specs with spring and after making a change to the code I get this error:

```
A copy of SupportAdmin::ApplicationAuthorizer has been removed from the module tree but is still active!
```

I think this is related to #178. My guess is the internal mapper needs to be cleared when reloading.

**Comment by tian-im** [comment]
I suspect this is related to #182

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.2 and see if it works for you? Now all the global methods that store Class have been replaced to store String instead and will be constantized as Class when called.

**Comment by ryanb** [comment]
Looks good, thanks!
