### ISSUE TITLE
Unable to perform "or" search with nil

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#183]
It appears searching `nil` in an "or" query does not work. For example: `foo:=nil` returns 1000 records, `foo:=nil,1` returns 0 records. Perhaps `nil` is interpreted as a string when in an "or" clause?

This is using `wallaby-active_record` v0.2.1.

**Comment by tian-im** [comment]
@ryanb see this release https://github.com/wallaby-rails/wallaby-active_record/releases/tag/0.2.2

please try to upgrade `wallaby-active_record` to `0.2.2` and let me know if it works for you or not.

**Comment by ryanb** [comment]
@tian-im nice, that fixes the case for `foo:=nil,1` however `foo:!=nil,1` does this query:

```
foo IS NOT NULL OR foo NOT IN ('1')
```

Which returns all records. If we do `foo:!=1,2` it returns all records except 1 and 2. To get that same behavior the `OR` should be an `AND` for `!=` case.

**Comment by tian-im** [comment]
@ryanb see this release https://github.com/wallaby-rails/wallaby-active_record/releases/tag/0.2.4

**Comment by tian-im** [comment]
please try to upgrade wallaby-active_record to 0.2.4 and let me know if it works for you or not.

**Comment by tian-im** [comment]
@ryanb could you upgrade wallaby to 6.1.1 and see if it works for you?

**Comment by ryanb** [comment]
@tian-im that seems to work well, thanks! Closing this.
