### ISSUE TITLE
Support Webpack

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#187]
We are moving all our app assets to Webpack(er) which means we only need Sprockets for Wallaby. It would be nice if Wallaby did not depend on Sprockets to reduce our app dependencies.

What about creating a node module for wallaby that we can require into our project which would include the JS dependencies and assets. Then add a config option for using webpack instead of sprockets.

Maybe move the sprockets portion into a `wallaby-sprockets` gem that one can use if they want the assets through sprockets.

What do you think?

**Comment by tian-im** [comment]
I'm not sure if Webpack is supported for a Rails engine, not from what I can see in Rails 5. But yeah, I can take a look and see if it can be done.

**Comment by ryanb** [comment]
From my understanding there's no way to add node dependencies through a gem so you can't use it through an engine the same way sprockets is used. You can still do it, but the the node dependency needs to be added separately.

For example, let's say you have a `wallaby-webpacker` gem which is designed to work with webpacker instead of sprockets. To install it you'd do:

```
gem install wallaby-webpacker
yarn add wallaby-rails # or whatever you name the module
```

Then they need to generate a pack file:

```js
// in app/javascript/packs/wallaby.js
import 'wallaby-rails'
```

Then the wallaby layout needs to link to that pack:

```
<%= stylesheet_pack_tag "wallaby", media: "all" %>
<%= javascript_pack_tag "wallaby" %>
```

Perhaps supply a generator to do these steps.

Why do we want this? Currently Wallaby depends on these gems: bootstrap, bootstrap4-datetime-picker-rails, jquery-rails, momentjs-rails, sass-rails, font-awesome-sass. These are all front-end dependencies and our app is using the node versions. This duplicates the dependencies of our app for all of these assets, and every deploy generates two copies of these dependencies: one through sprockets and another through webpack.

In theory we could remove sprockets entirely if wallaby didn't use it.

**Comment by tian-im** [comment]
Yeah, I totally understand why everyone wants it these days. Let me do some experiments and see.

**Comment by leomao10** [comment]
This is some extra information about how to include assets in engines:
https://github.com/rails/webpacker/blob/master/docs/engines.md

**Comment by tian-im** [comment]
@leomao10 try this: https://github.com/rails/webpacker/issues/348#issuecomment-635480949

**Comment by ryanb** [comment]
Since Webpacker is retired, I suggest not doing what I recommended above. I'm closing this issue.
