### ISSUE TITLE
Conflict with closure_tree

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#189]
I'm seeing this in our development log:

```
WALLABY DEBUG: Reloading after Rails' reload...
/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/closure_tree-7.1.0/lib/closure_tree/support.rb:36: warning: already initialized constant ObjectiveHierarchy
/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/closure_tree-7.1.0/lib/closure_tree/support.rb:36: warning: previous definition of ObjectiveHierarchy was here
/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/closure_tree-7.1.0/lib/closure_tree/support.rb:36: warning: already initialized constant OrgNodeHierarchy
/Users/rbates/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/closure_tree-7.1.0/lib/closure_tree/support.rb:36: warning: previous definition of OrgNodeHierarchy was here
```

It appears Wallaby is loading these classes which closure_tree doesn't expect. I tried adding the classes to Wallaby's `exclude` config but I still see these warnings. Can you make it so excluding models makes it so Wallaby doesn't attempt to require them?

**Comment by tian-im** [comment]
Hi @ryanb , I think this is an issue of `closure_tree`, if you take a look into https://github.com/ClosureTree/closure_tree/blob/master/lib/closure_tree/support.rb#L36, you will see that it creates a class and attaches to the parent class. This approach does not remove the class created when Rails reloads the parent class. Wallaby might have helped to surface this issue.

I can add a configuration not to require specific files/models, but I don't think it will resolve the issue of how a dynamic class should be created and removed in `closure_tree` in order to work with Rails reload.

**Comment by tian-im** [comment]
Let me double-check if any Class is still stored in `Wallaby::Map`. Is this issue for envisage?

**Comment by ryanb** [comment]
Yeah, this is for Envisage. The develop branch.

**Comment by ryanb** [comment]
Does wallaby attempt to load classes based on database tables? This may be the issue if so.

**Comment by tian-im** [comment]
Nope, Wallaby only loads the files under `eager_load_paths` which is the `/app` folder, it doesn't read the database tables.

Sure, I will take a look.

**Comment by tian-im** [comment]
@ryanb I can confirm that this is an issue of `closure_tree`, not `wallaby`.

I've tried to taken wallaby out completely from the `Gemfile`, `config/routes.rb`, `config/initializers/wallaby.rb`, and if I made any changes to `Objective` model and visited `GET "/objectives"`, when Rails reloaded, this warning came up. And if you take a look into the list of constants that Rails maintains by using:

```
ActiveSupport::Dependencies.autoloaded_constants
```

You will see that `Objective` is in the list, but the `ObjectiveHierarchy` created by `closure_tree` is not captured by Rails Dependencies. Therefore, on every reload, `ObjectiveHierarchy` will not be removed by Rails before it gets recreated.

**Comment by ryanb** [comment]
@tian-im oops, sorry about that. I tried removing wallaby as well and was not able to duplicate the warning. I'll close this ticket.

Thanks for taking the time to look into this.

**Comment by tian-im** [comment]
No worries :)

**Comment by ryanb** [comment]
FYI, I posted an issue here on closure_tree: https://github.com/ClosureTree/closure_tree/issues/362

**Comment by tian-im** [comment]
👌
