### ISSUE TITLE
Demo website sign in is not working

### ISSUE THREAD

**Issue by vittorius** [wallaby-rails/wallaby-rails#191]
Hey there!

Demo website sign-in is not working - redirecting to the same sign-in page:

![screencast 2020-05-15 10-44-45](https://user-images.githubusercontent.com/3304167/82025057-6fea2500-9699-11ea-8705-46be1576df8f.gif)

**Comment by tian-im** [comment]
Hi @vittorius, I'm checking it, thanks for letting me know :)

**Comment by tian-im** [comment]
@vittorius which browser are you using to open the demo website?

**Comment by vittorius** [comment]
Chrome 81.0.4044.138 (Official Build) (64-bit) on MacOS Catalina 10.15.4.

**Comment by tian-im** [comment]
Hmmm, same version. @vittorius could you try to use incognito mode to open it? It works fine for me.

Otherwise, is it possible to show me the network logs from the chrome inspector and see if any redirect is cached (e.g. network status is 3xx)?

**Comment by vittorius** [comment]
Incognito mode:
- status is `200 OK`
- [`sign_in` response](https://monosnap.com/file/xMcG6sl6IQKFYW4XXraBoJMzpmsPq1)
- request details [part 1](https://monosnap.com/file/9k5nLKWcyWeWz5kKnyH6ggItdnsb1x), [part 2](https://monosnap.com/file/kOaI3PSW5VpDKVUHB4LutTC3JAXhu2)
- the same picture persists no matter how many times you retry the sign-in

**Comment by tian-im** [comment]
Ha, I think I know what's going on. Will do a fix soon!

**Comment by tian-im** [comment]
thanks @vittorius

**Comment by tian-im** [comment]
It should be working fine now @vittorius 

Let me know if it's working for you.

Cheers!

**Comment by vittorius** [comment]
Yay! It works, thanks for the rapid reaction.

**Comment by tian-im** [comment]
no worries
