### ISSUE TITLE
Support for Devise >= v4

### ISSUE THREAD

**Issue by jpmcgrath** [wallaby-rails/wallaby-rails#2]
Hey @tian-im. Was hoping to use this gem in a project, but cannot because of a Devise compatibility (I am using Devise 4+). Any chance there is an easy work around?

**Comment by tian-im** [comment]
@jpmcgrath are you using the Devise 4+ with Rails 5? If yes, I'm planning to finish upgrading wallaby to support Rails 5 and apparently Devise 4+ in these two weeks and will keep you posted.

**Comment by jpmcgrath** [comment]
Still on Rails 4.2, but using Devise4+. Will probably upgrade to Rails5 someday soonish.

**Comment by tian-im** [comment]
@jpmcgrath see #3 for Rails 5 and release [4.1.5](https://github.com/reinteractive/wallaby/releases/tag/4.1.5) for Rails 4.2 with Devise 4

**Comment by jpmcgrath** [comment]
Thanks @tian-im I'll give it a go tomorrow.

**Comment by tian-im** [comment]
@jpmcgrath let me know how you'd go and feedbacks/feature requests are welcome!

**Comment by tian-im** [comment]
@jpmcgrath how did you go with wallaby? everything is ok?
