### ISSUE TITLE
Object is not decorated error in Rails 7.0.3

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#204]
I'm seeing this error when rendering a custom form action since upgrading to Rails 7.0.3. It works in Rails 7.0.2.4.

```
1.1) Failure/Error: <%= type_render decorated.form_type_of("trial_end_date"), field_name: "trial_end_date", form: form %>
    
    ActionView::Template::Error:
      Object is not decorated.
    # ./app/views/support_admin/accounts/extend_trial.html.erb:20:in `block in _app_views_support_admin_accounts_extend_trial_html_erb___2158087891327239296_1753240'
    # ./app/views/support_admin/accounts/extend_trial.html.erb:12:in `_app_views_support_admin_accounts_extend_trial_html_erb___2158087891327239296_1753240'
    # ./app/controllers/support_admin/accounts_controller.rb:3:in `extend_trial'
    # ./app/controllers/concerns/slow_request_concern.rb:14:in `notify_slow_requests'
    # ./app/controllers/application_controller.rb:82:in `set_time_zone!'
    # ------------------
    # --- Caused by: ---
    # ArgumentError:
    #   Object is not decorated.
    #   ./app/views/support_admin/accounts/extend_trial.html.erb:20:in `block in _app_views_support_admin_accounts_extend_trial_html_erb___2158087891327239296_1753240'
```

I'm uncertain why it says object is not decorated when it has `decorated = decorate resource` at the top of the template. Any ideas? Have you noticed this error in the latest version of Rails?

**Comment by ryanb** [comment]
@tian-im ping in case you don't get notified of new issues. :)

**Comment by tian-im** [comment]
yeah, please @ me. looking into that.

**Comment by tian-im** [comment]
it seems like 7.0.3 has introduced this change to convert object to model

https://github.com/rails/rails/compare/v7.0.2.4..7-0-stable#diff-44b94eca66c7497711821a8e6bcdfde4684bb7b8efa15e64da6532449f03ef0bR441

I'm going to do a fix and release it soon. Will keep you posted.

**Comment by tian-im** [comment]
@ryanb wallaby-core 0.2.7 is released, could you take a look and see if it works for you?

**Comment by ryanb** [comment]
@tian-im it works, thanks!
