### ISSUE TITLE
Mono Repo

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#215]
Would you consider merging the other wallaby repos into this one to make it a mono repo? It is difficult to know where to look for something and to see a complete commit history of changes. It would also be easier to add issues and submit PRs without wondering which repo to use. It would also allow you to make a single commit that changes multiple gems if the change depends on one another.

Feel free to disregard this if you like how the repos are organized.

**Comment by ryanb** [comment]
@tian-im ping in case you miss issue notifications.

**Comment by tian-im** [comment]
@ryanb I was thinking of merging other wallaby repos (e.g. `wallaby-core`, `wallaby-active_record` and/or `wallaby-view`) into a mono repo as they have quite a lot of tests and setup in common. `wallaby` gem/repo itself is more like a theme that contains only the ERB files, and I was thinking of moving my focus on implementing another theme using Tailwind CSS since it might help to make CSS overriding easier.

Do you think merging repos except `wallaby` makes sense to you?

**Comment by ryanb** [comment]
@tian-im to clarify, I was suggesting merging the repos, not gems. I was imagining directories under the Wallaby repo, one for each gem. Similar to the Rails repo. Then you can continue to keep everything separate but have one commit history and one place for issues and pull requests. It would be much easier to browse.

Just a thought, either way thanks for your work on this gem.

> I was thinking of moving my focus on implementing another theme using Tailwind CSS since it might help to make CSS overriding easier

If you're going through the effort of redoing everything with Tailwind I suggest making that the primary way instead of abstracting out themes. TW is much lighter when compiled, and since you're bundling the assets there aren't external dependencies so I don't see the reason for providing multiple themes. Someone extending can choose to use Tailwind or any CSS framework they want.

**Comment by tian-im** [comment]
Hi @ryanb

> to clarify, I was suggesting merging the repos, not gems. I was imagining directories under the Wallaby repo, one for each gem. Similar to the Rails repo. Then you can continue to keep everything separate but have one commit history and one place for issues and pull requests. It would be much easier to browse.

Yep, on the same page. I had a second thought and agreed that if I'm going to make a mono repo, I should include all of them.

Here is the mono repo https://github.com/wallaby-rails/wallaby-rails

Let me know WDYT?

**Comment by ryanb** [comment]
@tian-im yeah that's how I was thinking the mono repo look. 😄 

Please only do it if you like it yourself, not just on my account. It will make the project much easier to navigate from my perspective though.

**Comment by tian-im** [comment]
@ryanb Yeah, your suggestion is helpful as always 😁

I will archive the other repos afterward and move the issues to the new repo. It would be great if you can help to migrate them as well 😛

How's the `wallaby-7.0.0.beta2` gem? Is it working OK for you? I've recently updated the code to support custom routes for the nested-namespaced models as e.g. `order/items` over `order::items` in this PR at https://github.com/wallaby-rails/wallaby-rails/pull/1, let me know if you are interested to test it out.

**Comment by ryanb** [comment]
> It would be great if you can help to migrate them as well

Sure, do you want me to move my issues? Not sure how to do that.

> How's the wallaby-7.0.0.beta2 gem? Is it working OK for you? I've recently updated the code to support custom routes for the nested-namespaced models as e.g. order/items over order::items in this PR at https://github.com/wallaby-rails/wallaby-rails/pull/1, let me know if you are interested to test it out.

I got it running but had a couple issues to work on still. Unfortunately haven't had time. So far liking the direction though!

**Comment by ryanb** [comment]
@tian-im since most issues are on this `wallaby` repo, what about replacing this repo with the mono repo? Then you don't need to migrate the issues. It could also maintain some commit history if you want.

**Comment by tian-im** [comment]
That's a good idea! I can do that today.

**Comment by tian-im** [comment]
I've pushed up the mono repo to `wallaby-rails/wallaby`'s `main` branch and renamed it to `wallaby-rails/wallaby-rails`.

It seems good so far.

**Comment by ryanb** [comment]
Looks good! Thanks for doing this. Closing.
