### ISSUE TITLE
Application controller config not inherited

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#216]
I'm in the process of upgrading to wallaby 7.0.0 beta2 and having difficulty moving the config from the initializer to the application controller. The config settings aren't being inherited. For example I have this config.

```rb
module SupportAdmin
  # @see https://github.com/wallaby-rails/wallaby/blob/master/docs/controller.md
  class ApplicationController < Wallaby::ResourcesController
    #...
    self.model_authorizer = SupportAdmin::ApplicationAuthorizer
  end
end
```

And then another controller inheriting from it.

```rb
class SupportAdmin::AccountsController < SupportAdmin::ApplicationController
  # ...
end
```

The `model_authorizer` config isn't set on this controller.

```rb
SupportAdmin::ApplicationController.model_authorizer # => SupportAdmin::ApplicationAuthorizer
SupportAdmin::AccountsController.model_authorizer # => nil
```

This causes the authorization to not work from that controller.

**Comment by tian-im** [comment]
Looking into it

**Comment by tian-im** [comment]
Hmmm, could you change the line to:

```ruby
self.application_authorizer = SupportAdmin::ApplicationAuthorizer
```

I was thinking of using `application_authorizer` as the config that can be shared among parent and child classes, and `model_authorizer` as the only authorizer applied to a specific controller. Maybe I should consolidate these two configurations into one at some point to reduce the confusion.

**Comment by ryanb** [comment]
@tian-im that worked, thanks. I'll close this one.

> I was thinking of using application_authorizer as the config that can be shared among parent and child classes, and model_authorizer as the only authorizer applied to a specific controller. Maybe I should consolidate these two configurations into one at some point to reduce the confusion.

I don't see the need for having both. Can you override the setting in a subclass if you need it to be different?

**Comment by tian-im** [comment]
@ryanb Yes, you can override the `application_authorizer` in the subclass
