### ISSUE TITLE
Large Text in 7 Beta 2

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#217]
All of the text is larger when upgrading to Wallaby 7 beta 2 release. I believe this is because the `base/vars` scss isn't included before core so the variables aren't overridden.

**Comment by ryanb** [comment]
@tian-im ping^

**Comment by tian-im** [comment]
@ryanb see this PR https://github.com/wallaby-rails/wallaby-rails/pull/219

It should be fixed now. You can try it out by changing the `Gemfile` as:

```ruby
git 'https://github.com/wallaby-rails/wallaby-rails.git' do
  gem "wallaby"
  gem "wallaby-core"
  gem "wallaby-view"
  gem "wallaby-active_record"
end
```

Let me know if it works for you 🙇

**Comment by ryanb** [comment]
@tian-im LGTM, thanks!
