### ISSUE TITLE
Exception ignored when loading decorator

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#220]
If an exception is raised when loading a decorator (possibly other classes as well) it will be silently ignored and cause the decorator to fallback to the application decorator. For example:

```rb
class Admin::BlogDecorator < Admin::ApplicationDecorator
  foobar # Causes exception
end
```

This is in 7.0 beta 2.

@tian-im ping

**Comment by tian-im** [comment]
@ryanb Yeah, quite a few projects have classes that don't follow the naming convention, if Wallaby raises errors for this during preloading, it will require devs to correct the class names. In some of the big projects, it might lead to weird behaviors. But it was before `zeitwerk`, not sure if it's getting better now.

Do you think a warning message is enough or how do you see it best?

**Comment by ryanb** [comment]
@tian-im are you eating all exceptions? That's never a good idea IMO. Leads to very difficult to find bugs.

Can you detect the specific type of exception?

**Comment by tian-im** [comment]
@ryanb just the `NameError`, see the [source code](https://github.com/wallaby-rails/wallaby-rails/blob/main/wallaby-core/lib/wallaby/classifier.rb#L21-L29). Just all errors occurred during file loading will become `NameError` :sweat:, and there isn't really a way to distinguish if it's a name-not-matching-file error or a missing method error (e.g. in your example) as I can recall.

I will spend some time and see if the error messages can be different.

**Comment by tian-im** [comment]
Yeah, the errors all become `NameError` :(

**Comment by ryanb** [comment]
@tian-im ok, bummer. I wonder if zeitwerk could be improved to distinguish between these types of errors.

How about a config option to bubble up the errors?

**Comment by tian-im** [comment]
That can be done. Will spend some time this weekend on this.

**Comment by tian-im** [comment]
@ryanb the fix is merged (see https://github.com/wallaby-rails/wallaby-rails/pull/221), could you give it a try? 🙇 

```ruby
git 'https://github.com/wallaby-rails/wallaby-rails.git' do
  gem "wallaby"
  gem "wallaby-core"
  gem "wallaby-view"
  gem "wallaby-active_record"
end
```

**Comment by ryanb** [comment]
@tian-im looks like it's working, thanks!

I appreciate your work on this.

Too bad there's not a better way to check for the type of error than looking at the message content.

**Comment by tian-im** [comment]
@ryanb I've published the following gems:

- wallaby: 7.0.0
- wallaby-core: 0.3.0
- wallaby-active_record: 0.3.0

Could you give it a try? Cheers!

**Comment by ryanb** [comment]
Thanks! I'll try this on Friday.

**Comment by ryanb** [comment]
Have an issue with 7.0. See https://github.com/wallaby-rails/wallaby-rails/issues/222

**Comment by ryanb** [comment]
I'm reopening this since we had an issue with the app not starting in production since there was a name error in a custom servicer. This error doesn't show up in development/test since wallaby ignores the error.

Could there be an option to disable the dynamic Wallaby loading in all environments and manually reference the custom classes? Then just rely fully on Rails loading behavior.

**Comment by ryanb** [comment]
@tian-im I'm reopening this since we had an issue with the app not starting in production since there was a name error in a custom servicer. This error doesn't show up in development/test since wallaby ignores the error.

From my understanding, Wallaby needs to load classes dynamically since they aren't referenced directly in the app. The exception needs to be ignored in case the class doesn't exist. The work around to not ignore the error has performance issues.

Could there be an option to disable the dynamic Wallaby loading in all environments and manually reference the custom classes? Then just rely fully on Rails loading behavior.

**Comment by tian-im** [comment]
@ryanb You can manually reference all the custom classes from the controller, e.g.:

```ruby
class Admin::PostsController < Admin::ApplicationController
   self.model_servicer = Admin::PostServicer
   self.resource_decorator = Admin::PostDecorator
end
```

Just this only covers the cases for the current model (e.g. `Post`). For example, if there is an object in the view referencing a different model (e.g. `Blog`), then Wallaby still needs to dynamically guess the decorator class for this object by using `Wallaby::Guesser`.

I guess optimizing the `Wallaby::Guesser` should be the best option. I was thinking about this, maybe it's the time now, I will work on it during the weekends.

Do you need this urgently?

**Comment by ryanb** [comment]
@tian-im it's not urgent, I'm just wondering how to avoid the issue with production failing but dev/test passing.

Maybe I'll configure the CI server to eager load classes so it would behave like production. How about I do that before you invest too much time in this?

**Update:** This seems to work and I think is a better solution since this problem isn't really specific to Wallaby. If I have a name error in any class that the tests don't happen to load it would work in test but fail in production. Closing this one again.
