### ISSUE TITLE
"Create <Model>" links aren't shown as expected

### ISSUE THREAD

**Issue by lucascaton** [wallaby-rails/wallaby-rails#61]
Screencast:

> ![screen capture on 2018-01-03 at 15-38-47](https://user-images.githubusercontent.com/86755/34510095-93f34efe-f09c-11e7-9064-2c1282eef2f4.gif)

`Create #<Class:0x00007fe65b0243f8>`

**Comment by tian-im** [comment]
it's fixed in `5.1.0`
